- name: Add deploy user
  ansible.builtin.user:
    name: deploy
    shell: /bin/bash
    create_home: true

- name: Add SSH key for deploy user
  authorized_key:
    user: deploy
    key: "{{ lookup('file', 'files/dev_id_rsa.pub') }}"
    state: present
    manage_dir: true

- name: Set permissions for .ssh directory
  ansible.builtin.file:
    path: /home/deploy/.ssh
    owner: deploy
    group: deploy
    mode: "0700"
