- name: Ensure /home/developer directory exists
  ansible.builtin.file:
    path: /home/developer
    state: directory
    mode: '0755'

- name: Download Python 3.9.6
  ansible.builtin.get_url:
    url: https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz
    dest: /home/developer/Python-3.9.6.tgz
    mode: '0644'

- name: Extract Python
  ansible.builtin.unarchive:
    src: /home/developer/Python-3.9.6.tgz
    dest: /home/developer/
    remote_src: true

- name: Build and install Python
  ansible.builtin.shell: |
    cd /home/developer/Python-3.9.6 && ./configure --prefix=/opt/python3 && make && make install
  args:
    creates: /opt/python3/bin/python3.9

- name: Upgrade pip
  ansible.builtin.command:
    cmd: /opt/python3/bin/pip3.9 install --upgrade pip
  args:
    creates: /opt/python3/bin/pip3.9

- name: Install pip packages
  ansible.builtin.pip:
    executable: /opt/python3/bin/pip3.9
    name:
      - pycurl
      - mysqlclient
      - mysql-connector-python
      - certifi
      - redis
      - sentry-sdk
