- name: Add MySQL apt repo
  shell: |
    wget https://dev.mysql.com/get/mysql-apt-config_0.8.24-1_all.deb -O /tmp/mysql.deb && \
    echo "mysql-apt-config mysql-apt-config/select-server select mysql-5.7" | debconf-set-selections && \
    dpkg -i /tmp/mysql.deb
  args:
    creates: /etc/apt/sources.list.d/mysql.list

- name: Install MySQL Server
  debconf:
    name: "mysql-server"
    question: "mysql-server/root_password"
    value: "{{ mysql_root_password }}"
    vtype: "password"

- name: Confirm password
  debconf:
    name: "mysql-server"
    question: "mysql-server/root_password_again"
    value: "{{ mysql_root_password }}"
    vtype: "password"

- name: Install MySQL
  apt:
    name: mysql-server
    state: present