- name: Download MySQL apt repo
  ansible.builtin.get_url:
    url: https://repo.mysql.com/mysql-apt-config_0.8.34-1_all.deb
    dest: /tmp/mysql.deb
    mode: '0644'

- name: Ensure debconf-utils is installed
  ansible.builtin.apt:
    name: debconf-utils
    state: present
    update_cache: true

- name: Preseed MySQL 5.7 selection
  ansible.builtin.shell: |
    echo "mysql-apt-config mysql-apt-config/select-server select mysql-5.7" | debconf-set-selections
  args:
    executable: /bin/bash

- name: Install MySQL apt repo package
  ansible.builtin.shell: |
    dpkg -i /tmp/mysql.deb
  args:
    executable: /bin/bash
  register: dpkg_output
  failed_when: "'error' in dpkg_output.stderr.lower()"

- name: Update apt cache after adding MySQL repo
  ansible.builtin.apt:
    update_cache: true

- name: Preseed MySQL root password
  ansible.builtin.shell: |
    echo "mysql-server mysql-server/root_password password {{ mysql_root_password }}" | debconf-set-selections
    echo "mysql-server mysql-server/root_password_again password {{ mysql_root_password }}" | debconf-set-selections
  args:
    executable: /bin/bash

- name: Install MySQL Server
  ansible.builtin.apt:
    name: mysql-server
    state: present