- name: Install PHP
  ansible.builtin.apt:
    name: php
    state: present
    update_cache: true

- name: Download Composer installer
  ansible.builtin.get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php
    mode: "0644"

- name: Install Composer
  ansible.builtin.command: >
    php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: Move Composer
  ansible.builtin.command: mv /tmp/composer.phar /usr/local/bin/composer
  args:
    creates: /usr/local/bin/composer
