- name: Set timezone to UTC
  timezone:
    name: Etc/UTC

- name: Remove default user debian
  user:
    name: debian
    state: absent
    remove: yes

- name: Ensure dpkg is configured and not broken
  shell: dpkg --configure -a
  changed_when: false

- name: Clean APT cache
  apt:
    autoclean: yes
    autoremove: no
  changed_when: false

- name: Update APT cache
  apt:
    update_cache: yes  

- name: Install required packages
  apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: yes