- name: Set timezone to UTC
  ansible.builtin.command: timedatectl set-timezone UTC
  become: true

- name: Remove default user debian
  ansible.builtin.user:
    name: debian
    state: absent
    remove: true

- name: Install required packages
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: true
  register: install_result

- name: Show installed packages
  ansible.builtin.debug:
    msg: "Successfully installed packages: {{ install_result.packages if install_result.packages is defined else common_packages }}"
  when: install_result is succeeded
